name: Deploy demo to Github pages

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  push:
    branches: [ "demo" ]
  pull_request:
    branches: [ "demo" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Setup PNPM
      uses: pnpm/action-setup@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Setup Pages
      uses: actions/configure-pages@v5
      id: pages

    - run: pnpm install
    - run: pnpm run build
    - run: pnpm run build:demo

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: demo/

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment